server:
  port: 8080
spring:
  application:
    name: RestSample
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: root
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  version: 1.0.0